"""
Controlled stage-2 code generated by the platform.
Reason: stage2 controlled generator

Contract:
- Strategy code only emits signal columns.
- BacktestEngine owns fills, positions, costs, and trade records.
- Signals are confirmed on the current bar and executed by the engine on the next bar.
"""
import numpy as np
import pandas as pd


class Strategy:
    def __init__(self, params: dict):
        self.M = int(params.get("M", 20))
        self.N = int(params.get("N", 20))
        self.init_stop = float(params.get("init_stop", 0.02))
        self.K_min = float(params.get("K_min", 0.3))
        self.decay_step = float(params.get("decay_step", 0.1))
        self.max_position = int(params.get("max_position", 1))
        self.contract_multiplier = int(params.get("contract_multiplier", 10))
        self.commission_rate = float(params.get("commission_rate", 0.0001))
        self.slippage = float(params.get("slippage", 1.0))
        self.margin_rate = float(params.get("margin_rate", 0.08))

    def _vwma(self, price: pd.Series, volume: pd.Series, period: int) -> pd.Series:
        volume_sum = volume.rolling(period).sum().replace(0, np.nan)
        return (price * volume).rolling(period).sum() / volume_sum

    def compute_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        df = df.copy()
        close, high, low, volume = df["close"], df["high"], df["low"], df["volume"]
        df["vwma1"] = self._vwma(close, volume, self.M)
        df["vwma2"] = self._vwma(close, volume, self.M * 2)
        df["vwma3"] = self._vwma(close, volume, self.M * 3)
        # v1复现口径：多头侧记录VWMA1历史峰值，空头侧记录VWMA1历史谷值。
        # 原文没有给出完整条件状态机；平台会在阶段一和阶段四明确标记这是默认实现口径。
        df["vwma1_locked_long"] = df["vwma1"].cummax()
        df["vwma1_locked_short"] = df["vwma1"].cummin()
        price_change = close.diff()
        df["obv"] = (np.sign(price_change).fillna(0) * volume).cumsum()
        df["maobv"] = df["obv"].ewm(span=self.M, adjust=False).mean()
        for col in ["vwma1", "vwma2", "vwma3"]:
            df[col + "_slope"] = df[col].diff()
        df["n_high"] = high.rolling(self.N).max().shift(1)
        df["n_low"] = low.rolling(self.N).min().shift(1)
        return df

    def _entry_candidates(self, df: pd.DataFrame) -> pd.Series:
        trend_long = (df["close"].shift(1) > df["vwma3"].shift(1)) & (df["maobv"].shift(1) > df["maobv"].shift(2))
        trend_short = (df["close"].shift(1) < df["vwma3"].shift(1)) & (df["maobv"].shift(1) < df["maobv"].shift(2))
        long_shape = (
            (df["close"].shift(1) > df["vwma1_locked_long"].shift(1))
            & (df["close"].shift(1) > df["vwma2"].shift(1))
            & (df["close"].shift(1) > df["vwma3"].shift(1))
            & (df["vwma1"].shift(1) > df["vwma2"].shift(1))
            & (df["vwma2"].shift(1) > df["vwma3"].shift(1))
            & (df["vwma1_slope"].shift(1) > 0)
            & (df["vwma2_slope"].shift(1) > 0)
            & (df["vwma3_slope"].shift(1) > 0)
        )
        short_shape = (
            (df["close"].shift(1) < df["vwma1_locked_short"].shift(1))
            & (df["close"].shift(1) < df["vwma2"].shift(1))
            & (df["close"].shift(1) < df["vwma3"].shift(1))
            & (df["vwma1"].shift(1) < df["vwma2"].shift(1))
            & (df["vwma2"].shift(1) < df["vwma3"].shift(1))
            & (df["vwma1_slope"].shift(1) < 0)
            & (df["vwma2_slope"].shift(1) < 0)
            & (df["vwma3_slope"].shift(1) < 0)
        )
        signal = pd.Series(0, index=df.index, dtype=int)
        signal.loc[trend_long & long_shape & (df["close"] > df["n_high"])] = 1
        signal.loc[trend_short & short_shape & (df["close"] < df["n_low"])] = -1
        return signal

    def generate_signals(self, df: pd.DataFrame) -> pd.DataFrame:
        df = df.copy()
        raw_signal = self._entry_candidates(df)
        df["signal_raw"] = 0
        df["exit_signal"] = 0
        df["strategy_stop_price"] = 0.0
        df["strategy_k"] = np.nan
        df["strategy_trade_extreme"] = np.nan
        position = 0
        entry_price = 0.0
        entry_idx = 0
        trade_extreme = np.nan
        pending_entry = 0
        for i in range(len(df)):
            idx = df.index[i]
            row = df.iloc[i]
            if pending_entry != 0 and position == 0:
                position = pending_entry
                entry_price = float(row["open"])
                entry_idx = i
                trade_extreme = float(row["high"] if position == 1 else row["low"])
                pending_entry = 0
            if position != 0:
                bars_held = i - entry_idx
                k = max(1.0 - self.decay_step * bars_held, self.K_min)
                if position == 1:
                    trade_extreme = max(float(trade_extreme), float(row["high"]))
                    stop_price = max(entry_price * (1 - self.init_stop), trade_extreme * (1 - self.init_stop * k))
                    if bars_held > 0 and float(row["low"]) <= stop_price:
                        position = 0
                else:
                    trade_extreme = min(float(trade_extreme), float(row["low"]))
                    stop_price = min(entry_price * (1 + self.init_stop), trade_extreme * (1 + self.init_stop * k))
                    if bars_held > 0 and float(row["high"]) >= stop_price:
                        position = 0
                df.at[idx, "strategy_stop_price"] = stop_price
                df.at[idx, "strategy_k"] = k
                df.at[idx, "strategy_trade_extreme"] = trade_extreme
            if position == 0 and pending_entry == 0:
                candidate = int(raw_signal.iloc[i]) if pd.notna(raw_signal.iloc[i]) else 0
                if candidate != 0:
                    df.at[idx, "signal_raw"] = candidate
                    pending_entry = candidate
        return df

    def run(self, df: pd.DataFrame) -> pd.DataFrame:
        try:
            return self.generate_signals(self.compute_indicators(df))
        except Exception as exc:
            out = df.copy()
            out["signal_raw"] = 0
            out["exit_signal"] = 0
            out["strategy_stop_price"] = 0.0
            out["_error"] = str(exc)
            return out
