"""Deterministic stage-2 strategy code generator.

The AI may still draft code, but this module gives the platform a controlled
fallback path: read the stage-1 strategy spec, choose a known strategy family,
and emit code that follows the current BacktestEngine contract.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any


def _load_spec(strategy_dir: Path | None) -> dict[str, Any]:
    if not strategy_dir:
        return {}
    path = strategy_dir / "strategy_spec.json"
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _load_readme(strategy_dir: Path | None) -> str:
    if not strategy_dir:
        return ""
    path = strategy_dir / "README.md"
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8", errors="ignore")


def _spec_text(spec: dict[str, Any], readme: str) -> str:
    return (json.dumps(spec, ensure_ascii=False, default=str) + "\n" + (readme or "")).lower()


def _param_default(spec: dict[str, Any], names: list[str], fallback: Any) -> Any:
    wanted = {name.lower() for name in names}
    for row in spec.get("parameters") or []:
        if not isinstance(row, dict):
            continue
        name = str(row.get("name", "")).strip()
        if name.lower() not in wanted:
            continue
        value = row.get("default", fallback)
        if isinstance(fallback, bool):
            return str(value).lower() in {"1", "true", "yes", "y", "是"}
        if isinstance(fallback, int) and not isinstance(fallback, bool):
            match = re.search(r"-?\d+", str(value))
            return int(match.group(0)) if match else fallback
        if isinstance(fallback, float):
            match = re.search(r"-?\d+(?:\.\d+)?", str(value))
            return float(match.group(0)) if match else fallback
        return value
    return fallback


def _base_params(spec: dict[str, Any]) -> dict[str, Any]:
    return {
        "contract_multiplier": _param_default(spec, ["contract_multiplier", "合约乘数"], 10),
        "commission_rate": _param_default(spec, ["commission_rate", "手续费率"], 0.0001),
        "slippage": _param_default(spec, ["slippage", "滑点"], 1),
        "margin_rate": _param_default(spec, ["margin_rate", "保证金比例"], 0.08),
    }


def _preamble(reason: str) -> str:
    return f'''"""
Controlled stage-2 code generated by the platform.
Reason: {reason}

Contract:
- Strategy code only emits signal columns.
- BacktestEngine owns fills, positions, costs, and trade records.
- Signals are confirmed on the current bar and executed by the engine on the next bar.
"""
import numpy as np
import pandas as pd


'''


def _family(spec: dict[str, Any], readme: str) -> str:
    text = _spec_text(spec, readme)
    template_id = str(spec.get("template_id") or "").lower()
    if any(token in text for token in ["vwma", "obv", "maobv", "locked", "锁定", "能量潮"]):
        return "locked_vwma_obv"
    if any(token in text for token in ["斜率", "slope"]) and any(token in text for token in ["通道", "突破", "channel"]):
        return "ma_slope_breakout"
    if "turtle" in template_id or any(token in text for token in ["海龟", "super turtle", "donchian", "唐奇安", "atr"]):
        return "turtle_breakout"
    if any(token in text for token in ["expma", "ema", "指数移动平均"]):
        return "expma_cross"
    if any(token in text for token in ["双均线", "金叉", "死叉", "上穿", "下穿", "交叉"]):
        return "ma_cross"
    return ""


def generate_stage2_code(strategy_dir: Path | None, reason: str = "stage2 controlled fallback") -> tuple[str, dict[str, Any], str]:
    """Return (code, params, family). Empty code means no controlled template matched."""
    spec = _load_spec(strategy_dir)
    readme = _load_readme(strategy_dir)
    family = _family(spec, readme)
    if not family:
        return "", {}, ""
    if family == "locked_vwma_obv":
        params = _locked_vwma_params(spec)
        return _locked_vwma_code(params, reason), params, family
    if family == "ma_slope_breakout":
        params = _ma_slope_params(spec)
        return _ma_slope_code(params, reason), params, family
    if family == "turtle_breakout":
        params = _turtle_params(spec)
        return _turtle_code(params, reason), params, family
    if family in {"expma_cross", "ma_cross"}:
        params = _ma_cross_params(spec, use_ema=(family == "expma_cross"))
        return _ma_cross_code(params, reason), params, family
    return "", {}, ""


def _common_param_lines(params: dict[str, Any]) -> str:
    return "\n".join([
        f'        self.contract_multiplier = int(params.get("contract_multiplier", {int(params.get("contract_multiplier", 10))}))',
        f'        self.commission_rate = float(params.get("commission_rate", {float(params.get("commission_rate", 0.0001))}))',
        f'        self.slippage = float(params.get("slippage", {float(params.get("slippage", 1))}))',
        f'        self.margin_rate = float(params.get("margin_rate", {float(params.get("margin_rate", 0.08))}))',
    ])


def _locked_vwma_params(spec: dict[str, Any]) -> dict[str, Any]:
    params = _base_params(spec)
    params.update({
        "M": _param_default(spec, ["M", "ma_period"], 20),
        "N": _param_default(spec, ["N", "entry_period"], 20),
        "init_stop": _param_default(spec, ["init_stop", "initial_stop_pct"], 0.02),
        "K_min": _param_default(spec, ["K_min", "k_min"], 0.3),
        "decay_step": _param_default(spec, ["decay_step"], 0.1),
        "max_position": _param_default(spec, ["max_position"], 1),
    })
    return params


def _locked_vwma_code(params: dict[str, Any], reason: str) -> str:
    return _preamble(reason) + f'''class Strategy:
    def __init__(self, params: dict):
        self.M = int(params.get("M", {params["M"]}))
        self.N = int(params.get("N", {params["N"]}))
        self.init_stop = float(params.get("init_stop", {params["init_stop"]}))
        self.K_min = float(params.get("K_min", {params["K_min"]}))
        self.decay_step = float(params.get("decay_step", {params["decay_step"]}))
        self.max_position = int(params.get("max_position", {params["max_position"]}))
{_common_param_lines(params)}

    def _vwma(self, price: pd.Series, volume: pd.Series, period: int) -> pd.Series:
        volume_sum = volume.rolling(period).sum().replace(0, np.nan)
        return (price * volume).rolling(period).sum() / volume_sum

    def compute_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        df = df.copy()
        close, high, low, volume = df["close"], df["high"], df["low"], df["volume"]
        df["vwma1"] = self._vwma(close, volume, self.M)
        df["vwma2"] = self._vwma(close, volume, self.M * 2)
        df["vwma3"] = self._vwma(close, volume, self.M * 3)
        # v1复现口径：多头侧记录VWMA1历史峰值，空头侧记录VWMA1历史谷值。
        # 原文没有给出完整条件状态机；平台会在阶段一和阶段四明确标记这是默认实现口径。
        df["vwma1_locked_long"] = df["vwma1"].cummax()
        df["vwma1_locked_short"] = df["vwma1"].cummin()
        price_change = close.diff()
        df["obv"] = (np.sign(price_change).fillna(0) * volume).cumsum()
        df["maobv"] = df["obv"].ewm(span=self.M, adjust=False).mean()
        for col in ["vwma1", "vwma2", "vwma3"]:
            df[col + "_slope"] = df[col].diff()
        df["n_high"] = high.rolling(self.N).max().shift(1)
        df["n_low"] = low.rolling(self.N).min().shift(1)
        return df

    def _entry_candidates(self, df: pd.DataFrame) -> pd.Series:
        trend_long = (df["close"].shift(1) > df["vwma3"].shift(1)) & (df["maobv"].shift(1) > df["maobv"].shift(2))
        trend_short = (df["close"].shift(1) < df["vwma3"].shift(1)) & (df["maobv"].shift(1) < df["maobv"].shift(2))
        long_shape = (
            (df["close"].shift(1) > df["vwma1_locked_long"].shift(1))
            & (df["close"].shift(1) > df["vwma2"].shift(1))
            & (df["close"].shift(1) > df["vwma3"].shift(1))
            & (df["vwma1"].shift(1) > df["vwma2"].shift(1))
            & (df["vwma2"].shift(1) > df["vwma3"].shift(1))
            & (df["vwma1_slope"].shift(1) > 0)
            & (df["vwma2_slope"].shift(1) > 0)
            & (df["vwma3_slope"].shift(1) > 0)
        )
        short_shape = (
            (df["close"].shift(1) < df["vwma1_locked_short"].shift(1))
            & (df["close"].shift(1) < df["vwma2"].shift(1))
            & (df["close"].shift(1) < df["vwma3"].shift(1))
            & (df["vwma1"].shift(1) < df["vwma2"].shift(1))
            & (df["vwma2"].shift(1) < df["vwma3"].shift(1))
            & (df["vwma1_slope"].shift(1) < 0)
            & (df["vwma2_slope"].shift(1) < 0)
            & (df["vwma3_slope"].shift(1) < 0)
        )
        signal = pd.Series(0, index=df.index, dtype=int)
        signal.loc[trend_long & long_shape & (df["close"] > df["n_high"])] = 1
        signal.loc[trend_short & short_shape & (df["close"] < df["n_low"])] = -1
        return signal

    def generate_signals(self, df: pd.DataFrame) -> pd.DataFrame:
        df = df.copy()
        raw_signal = self._entry_candidates(df)
        df["signal_raw"] = 0
        df["exit_signal"] = 0
        df["strategy_stop_price"] = 0.0
        df["strategy_k"] = np.nan
        df["strategy_trade_extreme"] = np.nan
        position = 0
        entry_price = 0.0
        entry_idx = 0
        trade_extreme = np.nan
        pending_entry = 0
        for i in range(len(df)):
            idx = df.index[i]
            row = df.iloc[i]
            if pending_entry != 0 and position == 0:
                position = pending_entry
                entry_price = float(row["open"])
                entry_idx = i
                trade_extreme = float(row["high"] if position == 1 else row["low"])
                pending_entry = 0
            if position != 0:
                bars_held = i - entry_idx
                k = max(1.0 - self.decay_step * bars_held, self.K_min)
                if position == 1:
                    trade_extreme = max(float(trade_extreme), float(row["high"]))
                    stop_price = max(entry_price * (1 - self.init_stop), trade_extreme * (1 - self.init_stop * k))
                    if bars_held > 0 and float(row["low"]) <= stop_price:
                        position = 0
                else:
                    trade_extreme = min(float(trade_extreme), float(row["low"]))
                    stop_price = min(entry_price * (1 + self.init_stop), trade_extreme * (1 + self.init_stop * k))
                    if bars_held > 0 and float(row["high"]) >= stop_price:
                        position = 0
                df.at[idx, "strategy_stop_price"] = stop_price
                df.at[idx, "strategy_k"] = k
                df.at[idx, "strategy_trade_extreme"] = trade_extreme
            if position == 0 and pending_entry == 0:
                candidate = int(raw_signal.iloc[i]) if pd.notna(raw_signal.iloc[i]) else 0
                if candidate != 0:
                    df.at[idx, "signal_raw"] = candidate
                    pending_entry = candidate
        return df

    def run(self, df: pd.DataFrame) -> pd.DataFrame:
        try:
            return self.generate_signals(self.compute_indicators(df))
        except Exception as exc:
            out = df.copy()
            out["signal_raw"] = 0
            out["exit_signal"] = 0
            out["strategy_stop_price"] = 0.0
            out["_error"] = str(exc)
            return out
'''


def _ma_slope_params(spec: dict[str, Any]) -> dict[str, Any]:
    params = _base_params(spec)
    params.update({
        "N": _param_default(spec, ["N", "period", "entry_period"], 20),
        "slope_threshold": _param_default(spec, ["slope_threshold"], 0.0),
        "initial_stop_pct": _param_default(spec, ["initial_stop_pct", "init_stop"], 0.02),
        "K_min": _param_default(spec, ["K_min", "k_min"], 0.3),
        "decay_step": _param_default(spec, ["decay_step"], 0.1),
        "add_period": _param_default(spec, ["add_period"], 5),
        "max_add_positions": _param_default(spec, ["max_add_positions"], 1),
    })
    params["max_position"] = _param_default(spec, ["max_position"], 1 + int(params["max_add_positions"]))
    return params


def _ma_slope_code(params: dict[str, Any], reason: str) -> str:
    return _preamble(reason) + f'''class Strategy:
    def __init__(self, params: dict):
        self.N = int(params.get("N", {params["N"]}))
        self.slope_threshold = float(params.get("slope_threshold", {params["slope_threshold"]}))
        self.initial_stop_pct = float(params.get("initial_stop_pct", {params["initial_stop_pct"]}))
        self.K_min = float(params.get("K_min", {params["K_min"]}))
        self.decay_step = float(params.get("decay_step", {params["decay_step"]}))
        self.add_period = int(params.get("add_period", {params["add_period"]}))
        self.max_add_positions = int(params.get("max_add_positions", {params["max_add_positions"]}))
        self.max_position = int(params.get("max_position", {params["max_position"]}))
{_common_param_lines(params)}

    def compute_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        df = df.copy()
        df["ma"] = df["close"].rolling(self.N).mean()
        df["ma_slope"] = (df["ma"] - df["ma"].shift(self.N)) / self.N
        df["channel_high"] = df["high"].shift(1).rolling(self.N).max()
        df["channel_low"] = df["low"].shift(1).rolling(self.N).min()
        df["ma_short"] = df["close"].rolling(self.add_period).mean()
        return df

    def generate_signals(self, df: pd.DataFrame) -> pd.DataFrame:
        df = df.copy()
        df["signal_raw"] = 0
        df["exit_signal"] = 0
        df["strategy_stop_price"] = np.nan
        df["strategy_k"] = np.nan
        df["entry_reason"] = ""
        position = 0
        units = 0
        add_count = 0
        entry_price = np.nan
        entry_index = None
        pending_signal = 0
        stop_price = np.nan
        trade_extreme = np.nan
        for i in range(len(df)):
            idx = df.index[i]
            row = df.iloc[i]
            if pending_signal and position == 0:
                position = pending_signal
                units = 1
                add_count = 0
                entry_price = float(row["open"])
                entry_index = i
                trade_extreme = float(row["high"] if position == 1 else row["low"])
                stop_price = self._stop_from_extreme(position, entry_price, trade_extreme, 1.0)
                pending_signal = 0
            elif pending_signal and position == pending_signal and units < self.max_position:
                fill_price = float(row["open"])
                entry_price = (entry_price * units + fill_price) / (units + 1)
                units += 1
                add_count += 1
                entry_index = i
                trade_extreme = float(row["high"] if position == 1 else row["low"])
                stop_price = self._stop_from_extreme(position, entry_price, trade_extreme, 1.0)
                pending_signal = 0
            elif pending_signal and position == -pending_signal:
                position = pending_signal
                units = 1
                add_count = 0
                entry_price = float(row["open"])
                entry_index = i
                trade_extreme = float(row["high"] if position == 1 else row["low"])
                stop_price = self._stop_from_extreme(position, entry_price, trade_extreme, 1.0)
                pending_signal = 0

            if position:
                bars_held = max(0, i - (entry_index if entry_index is not None else i))
                k = max(1.0 - self.decay_step * bars_held, self.K_min)
                if position == 1:
                    trade_extreme = max(float(trade_extreme), float(row["high"]))
                else:
                    trade_extreme = min(float(trade_extreme), float(row["low"]))
                candidate_stop = self._stop_from_extreme(position, entry_price, trade_extreme, k)
                stop_price = candidate_stop if pd.isna(stop_price) else (max(stop_price, candidate_stop) if position == 1 else min(stop_price, candidate_stop))
                df.at[idx, "strategy_stop_price"] = stop_price
                df.at[idx, "strategy_k"] = k
                if (position == 1 and row["low"] <= stop_price) or (position == -1 and row["high"] >= stop_price):
                    position = 0
                    units = 0
                    add_count = 0
                    entry_price = np.nan
                    entry_index = None
                    stop_price = np.nan
                    trade_extreme = np.nan
                    continue

            long_condition = pd.notna(row["ma_slope"]) and pd.notna(row["channel_high"]) and row["ma_slope"] > self.slope_threshold and row["close"] > row["channel_high"]
            short_condition = pd.notna(row["ma_slope"]) and pd.notna(row["channel_low"]) and row["ma_slope"] < -self.slope_threshold and row["close"] < row["channel_low"]
            if position == 0:
                if long_condition:
                    df.at[idx, "signal_raw"] = 1
                    df.at[idx, "entry_reason"] = "long_slope_channel_breakout"
                    pending_signal = 1
                elif short_condition:
                    df.at[idx, "signal_raw"] = -1
                    df.at[idx, "entry_reason"] = "short_slope_channel_breakout"
                    pending_signal = -1
            elif position == 1:
                if short_condition:
                    df.at[idx, "signal_raw"] = -1
                    df.at[idx, "entry_reason"] = "reverse_to_short"
                    pending_signal = -1
                elif add_count < self.max_add_positions and units < self.max_position and self._long_add_condition(df, i, entry_price):
                    df.at[idx, "signal_raw"] = 1
                    df.at[idx, "entry_reason"] = "long_pullback_add"
                    pending_signal = 1
            elif position == -1:
                if long_condition:
                    df.at[idx, "signal_raw"] = 1
                    df.at[idx, "entry_reason"] = "reverse_to_long"
                    pending_signal = 1
                elif add_count < self.max_add_positions and units < self.max_position and self._short_add_condition(df, i, entry_price):
                    df.at[idx, "signal_raw"] = -1
                    df.at[idx, "entry_reason"] = "short_pullback_add"
                    pending_signal = -1
        return df

    def _stop_from_extreme(self, direction: int, entry_price: float, trade_extreme: float, k: float) -> float:
        if direction == 1:
            return max(entry_price * (1 - self.initial_stop_pct), trade_extreme * (1 - self.initial_stop_pct * k))
        return min(entry_price * (1 + self.initial_stop_pct), trade_extreme * (1 + self.initial_stop_pct * k))

    def _long_add_condition(self, df: pd.DataFrame, i: int, entry_price: float) -> bool:
        if i < 2 or pd.isna(entry_price):
            return False
        row, prev, prev2 = df.iloc[i], df.iloc[i - 1], df.iloc[i - 2]
        return row["close"] > entry_price and pd.notna(row["ma_short"]) and row["close"] < row["ma_short"] and pd.notna(prev["ma_short"]) and pd.notna(prev2["ma_short"]) and prev["close"] > prev2["ma_short"] and prev["close"] < prev["ma_short"]

    def _short_add_condition(self, df: pd.DataFrame, i: int, entry_price: float) -> bool:
        if i < 2 or pd.isna(entry_price):
            return False
        row, prev, prev2 = df.iloc[i], df.iloc[i - 1], df.iloc[i - 2]
        return row["close"] < entry_price and pd.notna(row["ma_short"]) and row["close"] > row["ma_short"] and pd.notna(prev["ma_short"]) and pd.notna(prev2["ma_short"]) and prev["close"] < prev2["ma_short"] and prev["close"] > prev["ma_short"]

    def run(self, df: pd.DataFrame) -> pd.DataFrame:
        try:
            return self.generate_signals(self.compute_indicators(df))
        except Exception as exc:
            out = df.copy()
            out["signal_raw"] = 0
            out["exit_signal"] = 0
            out["strategy_stop_price"] = 0.0
            out["_error"] = str(exc)
            return out
'''


def _turtle_params(spec: dict[str, Any]) -> dict[str, Any]:
    params = _base_params(spec)
    params.update({
        "entry_period": _param_default(spec, ["entry_period", "N"], 20),
        "exit_period": _param_default(spec, ["exit_period"], 10),
        "atr_period": _param_default(spec, ["atr_period"], 20),
        "stop_loss_atr": _param_default(spec, ["stop_loss_atr"], 2.0),
        "k": _param_default(spec, ["k"], 0.0),
        "max_position": _param_default(spec, ["max_position"], 1),
    })
    return params


def _turtle_code(params: dict[str, Any], reason: str) -> str:
    return _preamble(reason) + f'''class Strategy:
    def __init__(self, params: dict):
        self.entry_period = int(params.get("entry_period", {params["entry_period"]}))
        self.exit_period = int(params.get("exit_period", {params["exit_period"]}))
        self.atr_period = int(params.get("atr_period", {params["atr_period"]}))
        self.stop_loss_atr = float(params.get("stop_loss_atr", {params["stop_loss_atr"]}))
        self.k = float(params.get("k", {params["k"]}))
        self.max_position = int(params.get("max_position", {params["max_position"]}))
{_common_param_lines(params)}

    def compute_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        df = df.copy()
        prev_close = df["close"].shift(1)
        tr = pd.concat([(df["high"] - df["low"]).abs(), (df["high"] - prev_close).abs(), (df["low"] - prev_close).abs()], axis=1).max(axis=1)
        df["atr"] = tr.rolling(self.atr_period).mean()
        df["entry_high"] = df["high"].shift(1).rolling(self.entry_period).max()
        df["entry_low"] = df["low"].shift(1).rolling(self.entry_period).min()
        df["exit_high"] = df["high"].shift(1).rolling(self.exit_period).max()
        df["exit_low"] = df["low"].shift(1).rolling(self.exit_period).min()
        return df

    def generate_signals(self, df: pd.DataFrame) -> pd.DataFrame:
        df = df.copy()
        df["signal_raw"] = 0
        df["exit_signal"] = 0
        df["strategy_stop_price"] = np.nan
        position = 0
        entry_price = np.nan
        pending_signal = 0
        for i in range(len(df)):
            idx = df.index[i]
            row = df.iloc[i]
            if pending_signal and position == 0:
                position = pending_signal
                entry_price = float(row["open"])
                pending_signal = 0
            if position != 0:
                if position == 1:
                    stop_price = entry_price - self.stop_loss_atr * row["atr"] if pd.notna(row["atr"]) else np.nan
                    if pd.notna(stop_price):
                        df.at[idx, "strategy_stop_price"] = stop_price
                    if (pd.notna(row["exit_low"]) and row["close"] < row["exit_low"]) or (pd.notna(stop_price) and row["low"] <= stop_price):
                        df.at[idx, "exit_signal"] = 1
                        position = 0
                        entry_price = np.nan
                        continue
                else:
                    stop_price = entry_price + self.stop_loss_atr * row["atr"] if pd.notna(row["atr"]) else np.nan
                    if pd.notna(stop_price):
                        df.at[idx, "strategy_stop_price"] = stop_price
                    if (pd.notna(row["exit_high"]) and row["close"] > row["exit_high"]) or (pd.notna(stop_price) and row["high"] >= stop_price):
                        df.at[idx, "exit_signal"] = 1
                        position = 0
                        entry_price = np.nan
                        continue
            long_break = pd.notna(row["entry_high"]) and row["close"] > row["entry_high"] + self.k * (row["atr"] if pd.notna(row["atr"]) else 0)
            short_break = pd.notna(row["entry_low"]) and row["close"] < row["entry_low"] - self.k * (row["atr"] if pd.notna(row["atr"]) else 0)
            if position == 0:
                if long_break:
                    df.at[idx, "signal_raw"] = 1
                    pending_signal = 1
                elif short_break:
                    df.at[idx, "signal_raw"] = -1
                    pending_signal = -1
            elif position == 1 and short_break:
                df.at[idx, "signal_raw"] = -1
                pending_signal = -1
            elif position == -1 and long_break:
                df.at[idx, "signal_raw"] = 1
                pending_signal = 1
        return df

    def run(self, df: pd.DataFrame) -> pd.DataFrame:
        try:
            return self.generate_signals(self.compute_indicators(df))
        except Exception as exc:
            out = df.copy()
            out["signal_raw"] = 0
            out["exit_signal"] = 0
            out["strategy_stop_price"] = 0.0
            out["_error"] = str(exc)
            return out
'''


def _ma_cross_params(spec: dict[str, Any], use_ema: bool) -> dict[str, Any]:
    params = _base_params(spec)
    params.update({
        "short_period": _param_default(spec, ["short_period", "fast_ma", "P_short", "M"], 10),
        "long_period": _param_default(spec, ["long_period", "slow_ma", "P_long", "N"], 30),
        "use_ema": use_ema or _param_default(spec, ["use_ema"], False),
        "max_position": _param_default(spec, ["max_position"], 1),
    })
    return params


def _ma_cross_code(params: dict[str, Any], reason: str) -> str:
    use_ema_default = "True" if params["use_ema"] else "False"
    return _preamble(reason) + f'''class Strategy:
    def __init__(self, params: dict):
        self.short_period = int(params.get("short_period", {params["short_period"]}))
        self.long_period = int(params.get("long_period", {params["long_period"]}))
        self.use_ema = bool(params.get("use_ema", {use_ema_default}))
        self.max_position = int(params.get("max_position", {params["max_position"]}))
{_common_param_lines(params)}

    def compute_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        df = df.copy()
        if self.use_ema:
            df["ma_short"] = df["close"].ewm(span=self.short_period, adjust=False).mean()
            df["ma_long"] = df["close"].ewm(span=self.long_period, adjust=False).mean()
        else:
            df["ma_short"] = df["close"].rolling(self.short_period).mean()
            df["ma_long"] = df["close"].rolling(self.long_period).mean()
        return df

    def generate_signals(self, df: pd.DataFrame) -> pd.DataFrame:
        df = df.copy()
        prev_short = df["ma_short"].shift(1)
        prev_long = df["ma_long"].shift(1)
        golden = (df["ma_short"] > df["ma_long"]) & (prev_short <= prev_long)
        death = (df["ma_short"] < df["ma_long"]) & (prev_short >= prev_long)
        df["signal_raw"] = 0
        df["exit_signal"] = 0
        df.loc[golden, "signal_raw"] = 1
        df.loc[death, "signal_raw"] = -1
        return df

    def run(self, df: pd.DataFrame) -> pd.DataFrame:
        try:
            return self.generate_signals(self.compute_indicators(df))
        except Exception as exc:
            out = df.copy()
            out["signal_raw"] = 0
            out["exit_signal"] = 0
            out["_error"] = str(exc)
            return out
'''

