function E(id){return document.getElementById(id)}
function G(url){return fetch(url).then(function(r){return r.json()})}
function M(type,content){var d=document.createElement("div");d.className="msg "+type;d.innerHTML=mdToHtml(content);E("chat").appendChild(d);d.scrollIntoView({behavior:"smooth"})}
function esc(s){return s.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}
function mdToHtml(s){if(!s)return"";s=s.replace(/\*\*(.+?)\*\*/g,"<b>$1</b>");s=s.replace(/^## (.+)$/gm,"<h3>$1</h3>");return s}
async function goToStage(n){await fetch("/api/stage/switch?stage="+n,{method:"POST"});switchStage(n);E("inp").value="????"+n;send()}
async function switchStage(n){document.querySelectorAll(".stage").forEach(function(s){s.classList.remove("active")});var st=E("st"+n);if(st)st.classList.add("active");fetch("/api/stage/switch?stage="+n,{method:"POST"}).catch(function(){})}
function markStageDone(n){var st=E("st"+n);if(st)st.classList.add("done")}
function processStageContent(c){if(!c)return;if(c.indexOf("def compute_indicators")>=0||c.indexOf("total_trades")>=0||c.indexOf("trades_count")>=0){switchStage(3);markStageDone(1);markStageDone(2);markStageDone(3);E("body").innerHTML="<h2 class=st-title data-st=3></h2>"+mdToHtml(c)+"<p><button class=btn id=btnRerun onclick=runBT()></button></p>";return}else if(c.length>200){switchStage(1);markStageDone(1);E("body").innerHTML="<h2 class=st-title data-st=1></h2>"+mdToHtml(c);return}}
async function send(){var inp=E("inp"),text=inp.value.trim();if(!text)return;M("usr",text);inp.value="";var btn=E("sendBtn");btn.disabled=true;btn.textContent="...";try{var r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:[{role:"user",content:text}]})});var d=await r.json();var c=d.content||"";if(d.error)M("sys","<span class=neg>??: "+d.error+"</span>");else{M("sys",c);processStageContent(c)}}catch(e){M("sys","<span class=neg>????: "+e.message+"</span>")}btn.disabled=false;btn.textContent="??"}
async function loadOverview(){try{var sl=await G("/api/strategies");var sel=E("strategySelect");sel.innerHTML="";sl.forEach(function(s){sel.innerHTML+="<option value="+s.id+">"+s.id+"</option>"});var d=await G("/api/strategy");if(d.active)sel.value=d.active}catch(e){}}
async function switchStrategy(id){await fetch("/api/strategy/switch?id="+id,{method:"POST"});loadOverview();switchStage(1);E("body").innerHTML=""}
async function runBT(){var btn=document.querySelector(".btn");if(btn)btn.disabled=true;var r=await fetch("/api/backtest",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({symbol:"RB0",params:{}})});var d=await r.json();if(d.error){E("body").innerHTML="<span class=neg>??: "+d.error+"</span>";return}var s=d.details||{};var h="<h2 class=st-title data-st=3></h2><table><tr><th>??</th><th>??</th></tr><tr><td>???</td><td>"+(s.total_trades||0)+" ?</td></tr><tr><td>???</td><td class="+(s.net_profit>0?"pos":"neg")+">"+(s.net_profit||0).toLocaleString()+"</td></tr><tr><td>??</td><td>"+(s.win_rate?(s.win_rate*100).toFixed(1)+"%":"-")+"</td></tr><tr><td>????</td><td>"+(s.sharpe_ratio||"-")+"</td></tr><tr><td>????</td><td class=neg>"+(s.max_drawdown_pct?s.max_drawdown_pct.toFixed(2)+"%":"-")+"</td></tr><tr><td>???</td><td>"+(s.payoff_ratio||"-")+"</td></tr></table>";if(d.report_url)h+="<p><a href="+d.report_url+" target=_blank>??????</a></p>";E("body").innerHTML=h;switchStage(3);markStageDone(3);if(btn)btn.disabled=false}
function showSettings(){E("settingsModal").classList.add("show")}
function closeSettings(){E("settingsModal").classList.remove("show")}
async function saveSettings(){var key=E("apiKeyInput").value.trim();if(!key)return;await fetch("/api/config",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({api_key:key})});E("settingsStatus").textContent="???";setTimeout(closeSettings,1000)}
window.addEventListener("load",function(){loadOverview();try{G("/api/config").then(function(r){M("sys",r.api_key_set?"????AI????????????????????????????":"????API Key???????")}).catch(function(){})})